name: Count Lines

on:
  workflow_call:
    inputs:
      file_path:
        description: 'Path to the text file'
        required: true
        type: string

jobs:
  count_lines:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set execute permission for entrypoint.sh and run Line Counter Action
        run: |
          cd viond1002/dummy-action/line-counter
          chmod +x entrypoint.sh
          ./entrypoint.sh ${{ github.event.inputs.file_path }}

      - name: Run Line Counter Action
        uses: viond1002/dummy-action/line-counter/action.yaml@main
        with:
          file_path: ${{ github.event.inputs.file_path }}
