name: Reusable Workflow

on:
  workflow_call:
    inputs:
      who-to-greet:
        type: string
        required: true

jobs:
  hello_world_job:
    #runs-on: self-hosted
    name: A job to say hello
    steps:
      # To use the custom action from the dummy-action repository
      - name: Hello world action step
        uses: vinod1002/dummy-action/hello-world-docker-action@main # Uses an action from a different repository within the same organization
        with:
          who-to-greet: ${{ inputs.who-to-greet }}

      # Use the output from the custom action step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
