name: Test Custom Action

on:
  workflow_call:
    inputs:
      who-to-greet:
        type: string
        required: true

jobs:
  hello_world_job:
    runs-on: self-hosted
    name: A job to say hello
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Hello world action step
        id: hello_world_action
        uses: vinod1002/dummy-action/hello-world-docker-action/action.yaml@main
        with:
          who-to-greet: ${{ inputs.who-to-greet }}

      - name: Get the output time
        run: echo "The time was ${{ steps.hello_world_action.outputs.time }}"
